# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SmartTvPakistan' do
pod 'AFNetworking', '~> 3.0'
pod 'MFSideMenu'
pod 'CocoaLumberjack'
pod 'MBProgressHUD', '~> 0.9.1'
end

target 'SmartTvPakistanTests' do

end

target 'SmartTvPakistanUITests' do

end

